### ISSUE TITLE
About "Defining the Pose of any 3D Rigid Object and an Associated Distance"

### ISSUE THREAD

**Issue by rbregier** [dornik/plausible-poses#1]
Hi Dominik,

I just went through your ECCVW paper, thanks for sharing your research.

I am the main author of https://arxiv.org/abs/1612.04631 and I was surprised to read that you extended our proposed distance to handle symmetric objects.
The main purpose of our work was precisely to define a distance between poses of arbitrary rigid objects with arbitrary symmetries, which can be computed efficiently without having to rely on 'hacks' like sampling of proper symmetries.

Did you find a limitation in our approach, or is it due to a bad understanding of our work?
In the latter case, please feel free to reach out to me if some points are unclear.

Best,
Romain

EDIT / shameless advertisement:
the journal article is may be hard to read, but a practical summary can be found in section 4.1 of https://openaccess.thecvf.com/content_ICCV_2017_workshops/papers/w31/Bregier_Symmetry_Aware_Evaluation_ICCV_2017_paper.pdf

**Comment by dornik** [comment]
Hi Romain,

I think there is a misunderstanding as to which distance we extended. I understand that the paper may be unclear here, referring to it as the "metric used **for evaluation** in [your work]"; which is to indicate the baseline you defined in Eq. (98) of your work.

If you check [the code provided](https://github.com/dornik/plausible-poses/blob/e9688f5841401acbdfa85c38610cfa62c7a714cd/src/plausibility.py#L72) in this repository, the used distance and the required modification for our application should be evident too.

Best,
Dominik
